### PR TITLE
Add udf with reading local json job spec.

### PR DESCRIPTION
**Pull request by andyzhau**

### CODE REVIEW

**Comment by thesamet** [comment]
Thank you! Can you add address.json to the PR?

**Comment by andyzhau** [comment]
I think it's there. Just one line `{"foo": "bar"}`, which I used to map `foo` to a new `Address()`.

**Comment by thesamet** [comment]
My bad, I missed it before. Looks good, thanks for putting this together. I will take a look in the coming days.

**Comment by andyzhau** [comment]
No worries. Thanks for the quick response and great library!

**Pull request merged**
